stages: 
- build
- deploy 

image: edbizarro/gitlab-ci-pipeline-php:7.3
 
cache: 
  paths: 
    - laravel.repository/ 

composer: 
  stage: build 
  image: php:7.4-fpm  
  services: 
    - name: mysql:latest 
      alias: dbserver 
  variables: 
    MYSQL_DATABASE: docker 
    MYSQL_ROOT_PASSWORD: root     
  script: 
    - composer install 
    - cp .env.example .env 
    - php artisan key:generate 

  artifacts: 
    paths:
      - vendor/
      - .env
