stages: 
- build
- deploy 

cache: 
  paths: 
    - laravel.repository/ 

composer: 
  stage: build 
  image: php:7.4-fpm  
  services: 
    - name: mysql:latest 
      alias: dbserver 
  variables: 
    MYSQL_DATABASE: docker 
    MYSQL_ROOT_PASSWORD: root     
  script: 
    - php composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts 
    - cp .env.example .env 
    - php artisan key:generate 

  artifacts: 
    paths:
      - vendor/
      - .env
